export const NEW_CUSTOMER_REQUEST="NEW_CUSTOMER_REQUEST";
export const NEW_CUSTOMER_SUCCESS="NEW_CUSTOMER_SUCCESS";
export const NEW_CUSTOMER_FAIL="NEW_CUSTOMER_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";
export const ALL_CUSTOMERS_REQUEST="ALL_CUSTOMERS_REQUEST";
export const ALL_CUSTOMERS_SUCCESS="ALL_CUSTOMERS_SUCCESS";
export const ALL_CUSTOMERS_FAIL="ALL_CUSTOMERS_FAIL";


