export const NEW_ORDER_REQUEST="NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS="NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL="NEW_ORDER_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";
export const ALL_ORDER_REQUEST="ALL_ORDER_REQUEST";
export const ALL_ORDER_SUCCESS="ALL_ORDER_SUCCESS";
export const ALL_ORDER_FAIL="ALL_ORDER_FAIL";


